services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: ${DB_HOST:-postgressql-server-ghxxy3}
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-${POSTGRES_USER:-postgres}}
      DB_PASSWORD: ${DB_PASSWORD:-${POSTGRES_PASSWORD}}
      DB_DATABASE: veterinaria
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-8h}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - dokploy-network
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    # Quitamos la sección 'ports' expuesta para que no choque con Traefik
    networks:
      - dokploy-network
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`veterinaria-bowhru-10a5ca-149-50-139-62.sslip.io`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"      

networks:
  dokploy-network:
    external: true