services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgressql-server-ghxxy3
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: veterinaria
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-8h}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - dokploy-network # Para que pueda hablar con la red del panel
    labels:
          - traefik.docker.network=dokploy-network
          # ACTUALIZADO: Cambiado al nuevo dominio del backend
          - traefik.http.routers.veterinaria-veterinaria-bowhru-7-web.rule=Host(`veterinaria-bowhru-c0c7e0-149-50-139-62.sslip.io`)
          - traefik.http.routers.veterinaria-veterinaria-bowhru-7-web.entrypoints=web
          - traefik.http.services.veterinaria-veterinaria-bowhru-7-web.loadbalancer.server.port=3001
          - traefik.http.routers.veterinaria-veterinaria-bowhru-7-web.service=veterinaria-veterinaria-bowhru-7-web
          - traefik.enable=true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${APP_PORT:-5173}:5173"
    networks:
      - dokploy-network
      - default
    labels:
      - traefik.docker.network=dokploy-network
      # ACTUALIZADO: Cambiado al nuevo dominio del frontend
      - traefik.http.routers.veterinaria-veterinaria-bowhru-6-web.rule=Host(`veterinaria-bowhru-45e140-149-50-139-62.sslip.io`)
      - traefik.http.routers.veterinaria-veterinaria-bowhru-6-web.entrypoints=web
      # NOTA: Dejalo en 80 si tu contenedor de producción usa Nginx/Apache internamente para servir el build estático.
      # Si por el contrario levanta un servidor de desarrollo tipo Vite en producción, cambialo a 5173.
      - traefik.http.services.veterinaria-veterinaria-bowhru-6-web.loadbalancer.server.port=80
      - traefik.http.routers.veterinaria-veterinaria-bowhru-6-web.service=veterinaria-veterinaria-bowhru-6-web
      - traefik.enable=true      
    

networks:
  dokploy-network:
    external: true
